version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: bahnar-mongo
    ports:
      - "27017:27017"
    volumes:
      - bahnar-mongo-data:/data/db

  vncorenlp:
    build:
      context: ./BARTViBa/GraphTranslation/vncorenlp
    container_name: vncorenlp
    ports:
      - "9000:9000"

  bartviba:
    build:
      context: ./BARTViBa
    container_name: bartviba
    ports:
      - "10000:10000"
    depends_on:
      - vncorenlp
    environment:
      - VNCORENLP_URL=http://vncorenlp:9000

  backend:
    build:
      context: ./vietnamese-bahnaric-frontend-v3/bahnar-backend
    container_name: bahnar-backend
    ports:
      - "3501:3501"
    depends_on:
      - mongodb
      - bartviba
    environment:
      - PORT=3501
      - DB_URI=mongodb://mongodb:27017/bahnar-translator
      - SERVICE_NAME=bahnar-backend
      - TOKEN_TTL=7d
      - COOKIE_KEY=your_cookie_key
      - JWT_SECRET=your_jwt_secret
      - HASH_ROUNDS=10
      - BARTVIBA_URL=http://bartviba:10000

  frontend:
    build:
      context: ./vietnamese-bahnaric-frontend-v3/bahnar-web
    container_name: bahnar-web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3501

volumes:
  bahnar-mongo-data:
