# File: vietnamese-bahnaric-frontend-v3/bahnar-backend/Dockerfile
FROM node:16

WORKDIR /app

COPY vietnamese-bahnaric-frontend-v3/bahnar-backend /app

RUN npm install

EXPOSE 3501

CMD ["npm", "start"]
